const gcode = `
; G-Code generated by Simplify3D(R) Version 3.1.1
; Apr 9, 2017 at 4:07:40 PM
; Settings Summary
;   processName,Process1
;   applyToModels,cube
;   profileName,MakerBot Replicator 2 (modified)
;   profileVersion,2015-05-01 08:00:00
;   baseProfile,
;   printMaterial,PLA
;   printQuality,Fast
;   printExtruders,
;   extruderName,Primary Extruder
;   extruderToolheadNumber,0
;   extruderDiameter,0.4
;   extruderAutoWidth,0
;   extruderWidth,0.4
;   extrusionMultiplier,0.9
;   extruderUseRetract,1
;   extruderRetractionDistance,1
;   extruderExtraRestartDistance,0
;   extruderRetractionZLift,0
;   extruderRetractionSpeed,1200
;   extruderUseCoasting,0
;   extruderCoastingDistance,0.2
;   extruderUseWipe,0
;   extruderWipeDistance,5
;   primaryExtruder,0
;   layerHeight,0.3
;   topSolidLayers,0
;   bottomSolidLayers,0
;   perimeterOutlines,1
;   printPerimetersInsideOut,1
;   startPointOption,1
;   startPointOriginX,0
;   startPointOriginY,0
;   startPointOriginZ,300
;   sequentialIslands,0
;   spiralVaseMode,1
;   firstLayerHeightPercentage,90
;   firstLayerWidthPercentage,100
;   firstLayerUnderspeed,0.5
;   useRaft,0
;   raftExtruder,0
;   raftLayers,3
;   raftOffset,3
;   raftSeparationDistance,0.14
;   raftInfill,85
;   disableRaftBaseLayers,0
;   useSkirt,1
;   skirtExtruder,0
;   skirtLayers,1
;   skirtOutlines,2
;   skirtOffset,4
;   usePrimePillar,0
;   primePillarExtruder,999
;   primePillarWidth,12
;   primePillarLocation,7
;   primePillarSpeedMultiplier,1
;   useOozeShield,0
;   oozeShieldExtruder,999
;   oozeShieldOffset,2
;   oozeShieldOutlines,1
;   oozeShieldSidewallShape,1
;   oozeShieldSidewallAngle,30
;   oozeShieldSpeedMultiplier,1
;   infillExtruder,0
;   internalInfillPattern,Full Honeycomb
;   externalInfillPattern,Rectilinear
;   infillPercentage,0
;   outlineOverlapPercentage,20
;   infillExtrusionWidthPercentage,100
;   minInfillLength,5
;   infillLayerInterval,1
;   infillAngles,0,120,-120
;   overlapInfillAngles,0
;   generateSupport,0
;   supportExtruder,0
;   supportInfillPercentage,25
;   supportExtraInflation,0
;   denseSupportLayers,0
;   denseSupportInfillPercentage,70
;   supportLayerInterval,1
;   supportHorizontalPartOffset,0.3
;   supportUpperSeparationLayers,1
;   supportLowerSeparationLayers,1
;   supportType,0
;   supportGridSpacing,4
;   maxOverhangAngle,45
;   supportAngles,0
;   temperatureName,Primary Extruder
;   temperatureNumber,0
;   temperatureSetpointCount,1
;   temperatureSetpointLayers,1
;   temperatureSetpointTemperatures,230
;   temperatureStabilizeAtStartup,0
;   temperatureHeatedBed,0
;   temperatureRelayBetweenLayers,0
;   temperatureRelayBetweenLoops,0
;   fanLayers,1,2
;   fanSpeeds,0,100
;   blipFanToFullPower,0
;   adjustSpeedForCooling,1
;   minSpeedLayerTime,15
;   minCoolingSpeedSlowdown,20
;   increaseFanForCooling,0
;   minFanLayerTime,45
;   maxCoolingFanSpeed,100
;   increaseFanForBridging,0
;   bridgingFanSpeed,100
;   use5D,1
;   relativeEdistances,1
;   allowEaxisZeroing,0
;   independentExtruderAxes,1
;   includeM10123,0
;   stickySupport,1
;   applyToolheadOffsets,0
;   gcodeXoffset,0
;   gcodeYoffset,0
;   gcodeZoffset,0
;   overrideMachineDefinition,1
;   machineTypeOverride,0
;   strokeXoverride,280
;   strokeYoverride,150
;   strokeZoverride,150
;   originOffsetXoverride,140
;   originOffsetYoverride,75
;   originOffsetZoverride,0
;   homeXdirOverride,1
;   homeYdirOverride,1
;   homeZdirOverride,-1
;   flipXoverride,1
;   flipYoverride,-1
;   flipZoverride,1
;   toolheadOffsets,0,0|0,0|0,0|0,0|0,0|0,0
;   overrideFirmwareConfiguration,1
;   firmwareTypeOverride,MakerBot/Sailfish Firmware
;   GPXconfigOverride,r2
;   baudRateOverride,115200
;   overridePrinterModels,1
;   printerModelsOverride,MakerBot_Replicator2.stl
;   startingGcode,; **** Replicator 2 start.gcode ****,M73 P0 ; enable build progress,G162 X Y F3000 ; home XY maximum,G161 Z F1200 ; home Z minimum,G92 Z-5 ; set Z to -5,G1 Z0 ; move Z to 0,G161 Z F100 ; home Z slowly,M132 X Y Z A B ; recall home offsets,G1 X-145 Y-75 Z30 F9000 ; move to wait position off table,G130 X20 Y20 Z20 A20 B20 ; lower stepper Vrefs while heating,M126 S[fan_speed_pwm],M104 S[extruder0_temperature] T0,M133 T0 ; stabilize extruder temperature,G130 X127 Y127 Z40 A127 B127 ; default stepper Vrefs,G92 A0 ; zero extruder,G1 Z0.4 ; position nozzle,G1 E25 F300 ; purge nozzle,G1 X-140 Y-70 Z0.15 F1200 ; slow wipe,G1 X-135 Y-65 Z0.5 F1200 ; lift,G92 A0 ; zero extruder,M73 P1 ;@body (notify GPX body has started),; **** end of start.gcode ****
;   layerChangeGcode,
;   retractionGcode,
;   toolChangeGcode,
;   endingGcode,; **** Replicator 2 end.gcode ****,M73 P100 ; end build progress,G1 Z155 F1000 ; send Z axis to bottom of machine,M104 S0 T0 ; cool down extruder,M127 ; stop blower fan,G162 X Y F3000 ; home XY maximum,M18 ; disable stepper,M72 P1 ; play Ta-Da song,; **** end of end.gcode ****
;   exportFileFormat,x3g
;   celebration,0
;   celebrationSong,Random Song
;   postProcessing,
;   defaultSpeed,4800
;   outlineUnderspeed,0.5
;   solidInfillUnderspeed,0.8
;   supportUnderspeed,0.8
;   rapidXYspeed,9000
;   rapidZspeed,1200
;   minBridgingArea,50
;   bridgingExtraInflation,0
;   bridgingExtrusionMultiplier,1
;   bridgingSpeedMultiplier,0.8
;   filamentDiameter,1.75
;   filamentPricePerKg,46
;   filamentDensity,1.25
;   useMinPrintHeight,0
;   minPrintHeight,0
;   useMaxPrintHeight,0
;   maxPrintHeight,0
;   useDiaphragm,0
;   diaphragmLayerInterval,20
;   robustSlicing,1
;   mergeAllIntoSolid,0
;   onlyRetractWhenCrossingOutline,1
;   retractBetweenLayers,1
;   useRetractionMinTravel,0
;   retractionMinTravel,3
;   retractWhileWiping,0
;   onlyWipeOutlines,1
;   avoidCrossingOutline,0
;   maxMovementDetourFactor,3
;   toolChangeRetractionDistance,12
;   toolChangeExtraRestartDistance,-0.5
;   toolChangeRetractionSpeed,600
;   allowThinWallGapFill,1
;   thinWallAllowedOverlapPercentage,10
;   horizontalSizeCompensation,0
G90
M83
; **** Replicator 2 start.gcode ****
M73 P0 ; enable build progress
G162 X Y F3000 ; home XY maximum
G161 Z F1200 ; home Z minimum
G92 Z-5 ; set Z to -5
G1 Z0 ; move Z to 0
G161 Z F100 ; home Z slowly
M132 X Y Z A B ; recall home offsets
G1 X-145 Y-75 Z30 F9000 ; move to wait position off table
G130 X20 Y20 Z20 A20 B20 ; lower stepper Vrefs while heating
M127
M104 S230 T0
M133 T0 ; stabilize extruder temperature
G130 X127 Y127 Z40 A127 B127 ; default stepper Vrefs
G92 A0 ; zero extruder
G1 Z0.4 ; position nozzle
G1 E25 F300 ; purge nozzle
G1 X-140 Y-70 Z0.15 F1200 ; slow wipe
G1 X-135 Y-65 Z0.5 F1200 ; lift
G92 A0 ; zero extruder
M73 P1 ;@body (notify GPX body has started)
; **** end of start.gcode ****
G1 E-1.0000 F1200
G1 Z0.270 F1200
; layer 1, Z = 0.27
M135 T0
; tool H0.300 W0.400
; skirt
G1 X16.778 Y19.600 F9000
G1 E1.0000 F360
G1 X-16.778 Y19.600 E1.5067 F960
G1 X-16.999 Y19.509 E0.0107
G1 X-19.511 Y16.997 E0.1595
G1 X-19.602 Y16.776 E0.0107
G1 X-19.602 Y-16.776 E1.5065
G1 X-19.511 Y-16.997 E0.0107
G1 X-16.999 Y-19.509 E0.1595
G1 X-16.778 Y-19.600 E0.0107
G1 X16.778 Y-19.600 E1.5067
G1 X16.999 Y-19.509 E0.0107
G1 X19.511 Y-16.997 E0.1595
G1 X19.602 Y-16.776 E0.0107
G1 X19.602 Y16.776 E1.5065
G1 X19.511 Y16.997 E0.0107
G1 X16.999 Y19.509 E0.1595
G1 X16.778 Y19.600 E0.0107
G1 X16.699 Y19.200 F9000
G1 X-16.699 Y19.200 E1.4996 F960
G1 X-16.772 Y19.170 E0.0036
G1 X-19.172 Y16.770 E0.1524
G1 X-19.202 Y16.697 E0.0036
G1 X-19.202 Y-16.697 E1.4994
G1 X-19.172 Y-16.770 E0.0036
G1 X-16.772 Y-19.170 E0.1524
G1 X-16.699 Y-19.200 E0.0036
G1 X16.699 Y-19.200 E1.4996
G1 X16.772 Y-19.170 E0.0036
G1 X19.172 Y-16.770 E0.1524
G1 X19.202 Y-16.697 E0.0036
G1 X19.202 Y16.697 E1.4994
G1 X19.172 Y16.770 E0.0036
G1 X16.772 Y19.170 E0.1524
G1 X16.699 Y19.200 E0.0036
G1 E-1.0000 F1200
; outer perimeter
G1 X14.802 Y14.800 F9000
G1 E1.0000 F1200
G1 X-14.802 Y14.800 E1.3293 F480
G1 X-14.802 Y-14.800 E1.3291
G1 X14.802 Y-14.800 E1.3293
G1 X14.802 Y14.800 E1.3291
; layer 2, Z = 0.57
M126 S255
; outer perimeter
G1 X-14.802 Y14.800 F9000
G1 X-14.802 Y-14.800 Z0.270 E0.8307 F480
G1 X14.802 Y-14.800 Z0.345 E0.9969
G1 X14.802 Y14.800 Z0.420 E1.1629
G1 X-14.802 Y14.800 Z0.495 E1.3293
; layer 3, Z = 0.87
; outer perimeter
G1 X-14.802 Y-14.800 Z0.570 E1.3291 F480
G1 X14.802 Y-14.800 Z0.645 E1.3293
G1 X14.802 Y14.800 Z0.720 E1.3291
G1 X-14.802 Y14.800 Z0.795 E1.3293
; layer 4, Z = 1.17
; outer perimeter
G1 X-14.802 Y-14.800 Z0.870 E1.3291 F480
G1 X14.802 Y-14.800 Z0.945 E1.3293
G1 X14.802 Y14.800 Z1.020 E1.3291
G1 X-14.802 Y14.800 Z1.095 E1.3293
; layer 5, Z = 1.47
; outer perimeter
G1 X-14.802 Y-14.800 Z1.170 E1.3291 F480
G1 X14.802 Y-14.800 Z1.245 E1.3293
G1 X14.802 Y14.800 Z1.320 E1.3291
G1 X-14.802 Y14.800 Z1.395 E1.3293
; layer 6, Z = 1.77
; outer perimeter
G1 X-14.802 Y-14.800 Z1.470 E1.3291 F480
G1 X14.802 Y-14.800 Z1.545 E1.3293
G1 X14.802 Y14.800 Z1.620 E1.3291
G1 X-14.802 Y14.800 Z1.695 E1.3293
; layer 7, Z = 2.07
; outer perimeter
G1 X-14.802 Y-14.800 Z1.770 E1.3291 F480
G1 X14.802 Y-14.800 Z1.845 E1.3293
G1 X14.802 Y14.800 Z1.920 E1.3291
G1 X-14.802 Y14.800 Z1.995 E1.3293
; layer 8, Z = 2.37
; outer perimeter
G1 X-14.802 Y-14.800 Z2.070 E1.3291 F480
G1 X14.802 Y-14.800 Z2.145 E1.3293
G1 X14.802 Y14.800 Z2.220 E1.3291
G1 X-14.802 Y14.800 Z2.295 E1.3293
; layer 9, Z = 2.67
; outer perimeter
G1 X-14.802 Y-14.800 Z2.370 E1.3291 F480
G1 X14.802 Y-14.800 Z2.445 E1.3293
G1 X14.802 Y14.800 Z2.520 E1.3291
G1 X-14.802 Y14.800 Z2.595 E1.3293
; layer 10, Z = 2.97
; outer perimeter
G1 X-14.802 Y-14.800 Z2.670 E1.3291 F480
G1 X14.802 Y-14.800 Z2.745 E1.3293
G1 X14.802 Y14.800 Z2.820 E1.3291
G1 X-14.802 Y14.800 Z2.895 E1.3293
; layer 11, Z = 3.27
; outer perimeter
G1 X-14.802 Y-14.800 Z2.970 E1.3291 F480
G1 X14.802 Y-14.800 Z3.045 E1.3293
G1 X14.802 Y14.800 Z3.120 E1.3291
G1 X-14.802 Y14.800 Z3.195 E1.3293
; layer 12, Z = 3.57
; outer perimeter
G1 X-14.802 Y-14.800 Z3.270 E1.3291 F480
G1 X14.802 Y-14.800 Z3.345 E1.3293
G1 X14.802 Y14.800 Z3.420 E1.3291
G1 X-14.802 Y14.800 Z3.495 E1.3293
; layer 13, Z = 3.87
; outer perimeter
G1 X-14.802 Y-14.800 Z3.570 E1.3291 F480
G1 X14.802 Y-14.800 Z3.645 E1.3293
G1 X14.802 Y14.800 Z3.720 E1.3291
G1 X-14.802 Y14.800 Z3.795 E1.3293
; layer 14, Z = 4.17
; outer perimeter
G1 X-14.802 Y-14.800 Z3.870 E1.3291 F480
G1 X14.802 Y-14.800 Z3.945 E1.3293
G1 X14.802 Y14.800 Z4.020 E1.3291
G1 X-14.802 Y14.800 Z4.095 E1.3293
; layer 15, Z = 4.47
; outer perimeter
G1 X-14.802 Y-14.800 Z4.170 E1.3291 F480
G1 X14.802 Y-14.800 Z4.245 E1.3293
G1 X14.802 Y14.800 Z4.320 E1.3291
G1 X-14.802 Y14.800 Z4.395 E1.3293
; layer 16, Z = 4.77
; outer perimeter
G1 X-14.802 Y-14.800 Z4.470 E1.3291 F480
G1 X14.802 Y-14.800 Z4.545 E1.3293
G1 X14.802 Y14.800 Z4.620 E1.3291
G1 X-14.802 Y14.800 Z4.695 E1.3293
; layer 17, Z = 5.07
; outer perimeter
G1 X-14.802 Y-14.800 Z4.770 E1.3291 F480
G1 X14.802 Y-14.800 Z4.845 E1.3293
G1 X14.802 Y14.800 Z4.920 E1.3291
G1 X-14.802 Y14.800 Z4.995 E1.3293
; layer 18, Z = 5.37
; outer perimeter
G1 X-14.802 Y-14.800 Z5.070 E1.3291 F480
G1 X14.802 Y-14.800 Z5.145 E1.3293
G1 X14.802 Y14.800 Z5.220 E1.3291
G1 X-14.802 Y14.800 Z5.295 E1.3293
; layer 19, Z = 5.67
; outer perimeter
G1 X-14.802 Y-14.800 Z5.370 E1.3291 F480
G1 X14.802 Y-14.800 Z5.445 E1.3293
G1 X14.802 Y14.800 Z5.520 E1.3291
G1 X-14.802 Y14.800 Z5.595 E1.3293
; layer 20, Z = 5.97
; outer perimeter
G1 X-14.802 Y-14.800 Z5.670 E1.3291 F480
G1 X14.802 Y-14.800 Z5.745 E1.3293
G1 X14.802 Y14.800 Z5.820 E1.3291
G1 X-14.802 Y14.800 Z5.895 E1.3293
; layer 21, Z = 6.27
; outer perimeter
G1 X-14.802 Y-14.800 Z5.970 E1.3291 F480
G1 X14.802 Y-14.800 Z6.045 E1.3293
G1 X14.802 Y14.800 Z6.120 E1.3291
G1 X-14.802 Y14.800 Z6.195 E1.3293
; layer 22, Z = 6.57
; outer perimeter
G1 X-14.802 Y-14.800 Z6.270 E1.3291 F480
G1 X14.802 Y-14.800 Z6.345 E1.3293
G1 X14.802 Y14.800 Z6.420 E1.3291
G1 X-14.802 Y14.800 Z6.495 E1.3293
; layer 23, Z = 6.87
; outer perimeter
G1 X-14.802 Y-14.800 Z6.570 E1.3291 F480
G1 X14.802 Y-14.800 Z6.645 E1.3293
G1 X14.802 Y14.800 Z6.720 E1.3291
G1 X-14.802 Y14.800 Z6.795 E1.3293
; layer 24, Z = 7.17
; outer perimeter
G1 X-14.802 Y-14.800 Z6.870 E1.3291 F480
G1 X14.802 Y-14.800 Z6.945 E1.3293
G1 X14.802 Y14.800 Z7.020 E1.3291
G1 X-14.802 Y14.800 Z7.095 E1.3293
; layer 25, Z = 7.47
; outer perimeter
G1 X-14.802 Y-14.800 Z7.170 E1.3291 F480
G1 X14.802 Y-14.800 Z7.245 E1.3293
G1 X14.802 Y14.800 Z7.320 E1.3291
G1 X-14.802 Y14.800 Z7.395 E1.3293
; layer 26, Z = 7.77
; outer perimeter
G1 X-14.802 Y-14.800 Z7.470 E1.3291 F480
G1 X14.802 Y-14.800 Z7.545 E1.3293
G1 X14.802 Y14.800 Z7.620 E1.3291
G1 X-14.802 Y14.800 Z7.695 E1.3293
; layer 27, Z = 8.07
; outer perimeter
G1 X-14.802 Y-14.800 Z7.770 E1.3291 F480
G1 X14.802 Y-14.800 Z7.845 E1.3293
G1 X14.802 Y14.800 Z7.920 E1.3291
G1 X-14.802 Y14.800 Z7.995 E1.3293
; layer 28, Z = 8.37
; outer perimeter
G1 X-14.802 Y-14.800 Z8.070 E1.3291 F480
G1 X14.802 Y-14.800 Z8.145 E1.3293
G1 X14.802 Y14.800 Z8.220 E1.3291
G1 X-14.802 Y14.800 Z8.295 E1.3293
; layer 29, Z = 8.67
; outer perimeter
G1 X-14.802 Y-14.800 Z8.370 E1.3291 F480
G1 X14.802 Y-14.800 Z8.445 E1.3293
G1 X14.802 Y14.800 Z8.520 E1.3291
G1 X-14.802 Y14.800 Z8.595 E1.3293
; layer 30, Z = 8.97
; outer perimeter
G1 X-14.802 Y-14.800 Z8.670 E1.3291 F480
G1 X14.802 Y-14.800 Z8.745 E1.3293
G1 X14.802 Y14.800 Z8.820 E1.3291
G1 X-14.802 Y14.800 Z8.895 E1.3293
; layer 31, Z = 9.27
; outer perimeter
G1 X-14.802 Y-14.800 Z8.970 E1.3291 F480
G1 X14.802 Y-14.800 Z9.045 E1.3293
G1 X14.802 Y14.800 Z9.120 E1.3291
G1 X-14.802 Y14.800 Z9.195 E1.3293
; layer 32, Z = 9.57
; outer perimeter
G1 X-14.802 Y-14.800 Z9.270 E1.3291 F480
G1 X14.802 Y-14.800 Z9.345 E1.3293
G1 X14.802 Y14.800 Z9.420 E1.3291
G1 X-14.802 Y14.800 Z9.495 E1.3293
; layer 33, Z = 9.87
; outer perimeter
G1 X-14.802 Y-14.800 Z9.570 E1.3291 F480
G1 X14.802 Y-14.800 Z9.645 E1.3293
G1 X14.802 Y14.800 Z9.720 E1.3291
G1 X-14.802 Y14.800 Z9.795 E1.3293
; layer 34, Z = 10.17
; outer perimeter
G1 X-14.802 Y-14.800 Z9.870 E1.3291 F480
G1 X14.802 Y-14.800 Z9.945 E1.3293
G1 X14.802 Y14.800 Z10.020 E1.3291
G1 X-14.802 Y14.800 Z10.095 E1.3293
; layer 35, Z = 10.47
; outer perimeter
G1 X-14.802 Y-14.800 Z10.170 E1.3291 F480
G1 X14.802 Y-14.800 Z10.245 E1.3293
G1 X14.802 Y14.800 Z10.320 E1.3291
G1 X-14.802 Y14.800 Z10.395 E1.3293
; layer 36, Z = 10.77
; outer perimeter
G1 X-14.802 Y-14.800 Z10.470 E1.3291 F480
G1 X14.802 Y-14.800 Z10.545 E1.3293
G1 X14.802 Y14.800 Z10.620 E1.3291
G1 X-14.802 Y14.800 Z10.695 E1.3293
; layer 37, Z = 11.07
; outer perimeter
G1 X-14.802 Y-14.800 Z10.770 E1.3291 F480
G1 X14.802 Y-14.800 Z10.845 E1.3293
G1 X14.802 Y14.800 Z10.920 E1.3291
G1 X-14.802 Y14.800 Z10.995 E1.3293
; layer 38, Z = 11.37
; outer perimeter
G1 X-14.802 Y-14.800 Z11.070 E1.3291 F480
G1 X14.802 Y-14.800 Z11.145 E1.3293
G1 X14.802 Y14.800 Z11.220 E1.3291
G1 X-14.802 Y14.800 Z11.295 E1.3293
; layer 39, Z = 11.67
; outer perimeter
G1 X-14.802 Y-14.800 Z11.370 E1.3291 F480
G1 X14.802 Y-14.800 Z11.445 E1.3293
G1 X14.802 Y14.800 Z11.520 E1.3291
G1 X-14.802 Y14.800 Z11.595 E1.3293
; layer 40, Z = 11.97
; outer perimeter
G1 X-14.802 Y-14.800 Z11.670 E1.3291 F480
G1 X14.802 Y-14.800 Z11.745 E1.3293
G1 X14.802 Y14.800 Z11.820 E1.3291
G1 X-14.802 Y14.800 Z11.895 E1.3293
; layer 41, Z = 12.27
; outer perimeter
G1 X-14.802 Y-14.800 Z11.970 E1.3291 F480
G1 X14.802 Y-14.800 Z12.045 E1.3293
G1 X14.802 Y14.800 Z12.120 E1.3291
G1 X-14.802 Y14.800 Z12.195 E1.3293
; layer 42, Z = 12.57
; outer perimeter
G1 X-14.802 Y-14.800 Z12.270 E1.3291 F480
G1 X14.802 Y-14.800 Z12.345 E1.3293
G1 X14.802 Y14.800 Z12.420 E1.3291
G1 X-14.802 Y14.800 Z12.495 E1.3293
; layer 43, Z = 12.87
; outer perimeter
G1 X-14.802 Y-14.800 Z12.570 E1.3291 F480
G1 X14.802 Y-14.800 Z12.645 E1.3293
G1 X14.802 Y14.800 Z12.720 E1.3291
G1 X-14.802 Y14.800 Z12.795 E1.3293
; layer 44, Z = 13.17
; outer perimeter
G1 X-14.802 Y-14.800 Z12.870 E1.3291 F480
G1 X14.802 Y-14.800 Z12.945 E1.3293
G1 X14.802 Y14.800 Z13.020 E1.3291
G1 X-14.802 Y14.800 Z13.095 E1.3293
; layer 45, Z = 13.47
; outer perimeter
G1 X-14.802 Y-14.800 Z13.170 E1.3291 F480
G1 X14.802 Y-14.800 Z13.245 E1.3293
G1 X14.802 Y14.800 Z13.320 E1.3291
G1 X-14.802 Y14.800 Z13.395 E1.3293
; layer 46, Z = 13.77
; outer perimeter
G1 X-14.802 Y-14.800 Z13.470 E1.3291 F480
G1 X14.802 Y-14.800 Z13.545 E1.3293
G1 X14.802 Y14.800 Z13.620 E1.3291
G1 X-14.802 Y14.800 Z13.695 E1.3293
; layer 47, Z = 14.07
; outer perimeter
G1 X-14.802 Y-14.800 Z13.770 E1.3291 F480
G1 X14.802 Y-14.800 Z13.845 E1.3293
G1 X14.802 Y14.800 Z13.920 E1.3291
G1 X-14.802 Y14.800 Z13.995 E1.3293
; layer 48, Z = 14.37
; outer perimeter
G1 X-14.802 Y-14.800 Z14.070 E1.3291 F480
G1 X14.802 Y-14.800 Z14.145 E1.3293
G1 X14.802 Y14.800 Z14.220 E1.3291
G1 X-14.802 Y14.800 Z14.295 E1.3293
; layer 49, Z = 14.67
; outer perimeter
G1 X-14.802 Y-14.800 Z14.370 E1.3291 F480
G1 X14.802 Y-14.800 Z14.445 E1.3293
G1 X14.802 Y14.800 Z14.520 E1.3291
G1 X-14.802 Y14.800 Z14.595 E1.3293
; layer 50, Z = 14.97
; outer perimeter
G1 X-14.802 Y-14.800 Z14.670 E1.3291 F480
G1 X14.802 Y-14.800 Z14.745 E1.3293
G1 X14.802 Y14.800 Z14.820 E1.3291
G1 X-14.802 Y14.800 Z14.895 E1.3293
; layer 51, Z = 15.27
; outer perimeter
G1 X-14.802 Y-14.800 Z14.970 E1.3291 F480
G1 X14.802 Y-14.800 Z15.045 E1.3293
G1 X14.802 Y14.800 Z15.120 E1.3291
G1 X-14.802 Y14.800 Z15.195 E1.3293
; layer 52, Z = 15.57
; outer perimeter
G1 X-14.802 Y-14.800 Z15.270 E1.3291 F480
G1 X14.802 Y-14.800 Z15.345 E1.3293
G1 X14.802 Y14.800 Z15.420 E1.3291
G1 X-14.802 Y14.800 Z15.495 E1.3293
; layer 53, Z = 15.87
; outer perimeter
G1 X-14.802 Y-14.800 Z15.570 E1.3291 F480
G1 X14.802 Y-14.800 Z15.645 E1.3293
G1 X14.802 Y14.800 Z15.720 E1.3291
G1 X-14.802 Y14.800 Z15.795 E1.3293
; layer 54, Z = 16.17
; outer perimeter
G1 X-14.802 Y-14.800 Z15.870 E1.3291 F480
G1 X14.802 Y-14.800 Z15.945 E1.3293
G1 X14.802 Y14.800 Z16.020 E1.3291
G1 X-14.802 Y14.800 Z16.095 E1.3293
; layer 55, Z = 16.47
; outer perimeter
G1 X-14.802 Y-14.800 Z16.170 E1.3291 F480
G1 X14.802 Y-14.800 Z16.245 E1.3293
G1 X14.802 Y14.800 Z16.320 E1.3291
G1 X-14.802 Y14.800 Z16.395 E1.3293
; layer 56, Z = 16.77
; outer perimeter
G1 X-14.802 Y-14.800 Z16.470 E1.3291 F480
G1 X14.802 Y-14.800 Z16.545 E1.3293
G1 X14.802 Y14.800 Z16.620 E1.3291
G1 X-14.802 Y14.800 Z16.695 E1.3293
; layer 57, Z = 17.07
; outer perimeter
G1 X-14.802 Y-14.800 Z16.770 E1.3291 F480
G1 X14.802 Y-14.800 Z16.845 E1.3293
G1 X14.802 Y14.800 Z16.920 E1.3291
G1 X-14.802 Y14.800 Z16.995 E1.3293
; layer 58, Z = 17.37
; outer perimeter
G1 X-14.802 Y-14.800 Z17.070 E1.3291 F480
G1 X14.802 Y-14.800 Z17.145 E1.3293
G1 X14.802 Y14.800 Z17.220 E1.3291
G1 X-14.802 Y14.800 Z17.295 E1.3293
; layer 59, Z = 17.67
; outer perimeter
G1 X-14.802 Y-14.800 Z17.370 E1.3291 F480
G1 X14.802 Y-14.800 Z17.445 E1.3293
G1 X14.802 Y14.800 Z17.520 E1.3291
G1 X-14.802 Y14.800 Z17.595 E1.3293
; layer 60, Z = 17.97
; outer perimeter
G1 X-14.802 Y-14.800 Z17.670 E1.3291 F480
G1 X14.802 Y-14.800 Z17.745 E1.3293
G1 X14.802 Y14.800 Z17.820 E1.3291
G1 X-14.802 Y14.800 Z17.895 E1.3293
; layer 61, Z = 18.27
; outer perimeter
G1 X-14.802 Y-14.800 Z17.970 E1.3291 F480
G1 X14.802 Y-14.800 Z18.045 E1.3293
G1 X14.802 Y14.800 Z18.120 E1.3291
G1 X-14.802 Y14.800 Z18.195 E1.3293
; layer 62, Z = 18.57
; outer perimeter
G1 X-14.802 Y-14.800 Z18.270 E1.3291 F480
G1 X14.802 Y-14.800 Z18.345 E1.3293
G1 X14.802 Y14.800 Z18.420 E1.3291
G1 X-14.802 Y14.800 Z18.495 E1.3293
; layer 63, Z = 18.87
; outer perimeter
G1 X-14.802 Y-14.800 Z18.570 E1.3291 F480
G1 X14.802 Y-14.800 Z18.645 E1.3293
G1 X14.802 Y14.800 Z18.720 E1.3291
G1 X-14.802 Y14.800 Z18.795 E1.3293
; layer 64, Z = 19.17
; outer perimeter
G1 X-14.802 Y-14.800 Z18.870 E1.3291 F480
G1 X14.802 Y-14.800 Z18.945 E1.3293
G1 X14.802 Y14.800 Z19.020 E1.3291
G1 X-14.802 Y14.800 Z19.095 E1.3293
; layer 65, Z = 19.47
; outer perimeter
G1 X-14.802 Y-14.800 Z19.170 E1.3291 F480
G1 X14.802 Y-14.800 Z19.245 E1.3293
G1 X14.802 Y14.800 Z19.320 E1.3291
G1 X-14.802 Y14.800 Z19.395 E1.3293
; layer 66, Z = 19.77
; outer perimeter
G1 X-14.802 Y-14.800 Z19.470 E1.3291 F480
G1 X14.802 Y-14.800 Z19.545 E1.3293
G1 X14.802 Y14.800 Z19.620 E1.3291
G1 X-14.802 Y14.800 Z19.695 E1.3293
; layer 67, Z = 20.07
; outer perimeter
G1 X-14.802 Y-14.800 Z19.770 E1.3291 F480
G1 X14.802 Y-14.800 Z19.845 E1.3293
G1 X14.802 Y14.800 Z19.920 E1.3291
G1 X-14.802 Y14.800 Z19.995 E1.3293
; layer 68, Z = 20.37
; outer perimeter
G1 X-14.802 Y-14.800 Z20.070 E1.3291 F480
G1 X14.802 Y-14.800 Z20.145 E1.3293
G1 X14.802 Y14.800 Z20.220 E1.3291
G1 X-14.802 Y14.800 Z20.295 E1.3293
; layer 69, Z = 20.67
; outer perimeter
G1 X-14.802 Y-14.800 Z20.370 E1.3291 F480
G1 X14.802 Y-14.800 Z20.445 E1.3293
G1 X14.802 Y14.800 Z20.520 E1.3291
G1 X-14.802 Y14.800 Z20.595 E1.3293
; layer 70, Z = 20.97
; outer perimeter
G1 X-14.802 Y-14.800 Z20.670 E1.3291 F480
G1 X14.802 Y-14.800 Z20.745 E1.3293
G1 X14.802 Y14.800 Z20.820 E1.3291
G1 X-14.802 Y14.800 Z20.895 E1.3293
; layer 71, Z = 21.27
; outer perimeter
G1 X-14.802 Y-14.800 Z20.970 E1.3291 F480
G1 X14.802 Y-14.800 Z21.045 E1.3293
G1 X14.802 Y14.800 Z21.120 E1.3291
G1 X-14.802 Y14.800 Z21.195 E1.3293
; layer 72, Z = 21.57
; outer perimeter
G1 X-14.802 Y-14.800 Z21.270 E1.3291 F480
G1 X14.802 Y-14.800 Z21.345 E1.3293
G1 X14.802 Y14.800 Z21.420 E1.3291
G1 X-14.802 Y14.800 Z21.495 E1.3293
; layer 73, Z = 21.87
; outer perimeter
G1 X-14.802 Y-14.800 Z21.570 E1.3291 F480
G1 X14.802 Y-14.800 Z21.645 E1.3293
G1 X14.802 Y14.800 Z21.720 E1.3291
G1 X-14.802 Y14.800 Z21.795 E1.3293
; layer 74, Z = 22.17
; outer perimeter
G1 X-14.802 Y-14.800 Z21.870 E1.3291 F480
G1 X14.802 Y-14.800 Z21.945 E1.3293
G1 X14.802 Y14.800 Z22.020 E1.3291
G1 X-14.802 Y14.800 Z22.095 E1.3293
; layer 75, Z = 22.47
; outer perimeter
G1 X-14.802 Y-14.800 Z22.170 E1.3291 F480
G1 X14.802 Y-14.800 Z22.245 E1.3293
G1 X14.802 Y14.800 Z22.320 E1.3291
G1 X-14.802 Y14.800 Z22.395 E1.3293
; layer 76, Z = 22.77
; outer perimeter
G1 X-14.802 Y-14.800 Z22.470 E1.3291 F480
G1 X14.802 Y-14.800 Z22.545 E1.3293
G1 X14.802 Y14.800 Z22.620 E1.3291
G1 X-14.802 Y14.800 Z22.695 E1.3293
; layer 77, Z = 23.07
; outer perimeter
G1 X-14.802 Y-14.800 Z22.770 E1.3291 F480
G1 X14.802 Y-14.800 Z22.845 E1.3293
G1 X14.802 Y14.800 Z22.920 E1.3291
G1 X-14.802 Y14.800 Z22.995 E1.3293
; layer 78, Z = 23.37
; outer perimeter
G1 X-14.802 Y-14.800 Z23.070 E1.3291 F480
G1 X14.802 Y-14.800 Z23.145 E1.3293
G1 X14.802 Y14.800 Z23.220 E1.3291
G1 X-14.802 Y14.800 Z23.295 E1.3293
; layer 79, Z = 23.67
; outer perimeter
G1 X-14.802 Y-14.800 Z23.370 E1.3291 F480
G1 X14.802 Y-14.800 Z23.445 E1.3293
G1 X14.802 Y14.800 Z23.520 E1.3291
G1 X-14.802 Y14.800 Z23.595 E1.3293
; layer 80, Z = 23.97
; outer perimeter
G1 X-14.802 Y-14.800 Z23.670 E1.3291 F480
G1 X14.802 Y-14.800 Z23.745 E1.3293
G1 X14.802 Y14.800 Z23.820 E1.3291
G1 X-14.802 Y14.800 Z23.895 E1.3293
; layer 81, Z = 24.27
; outer perimeter
G1 X-14.802 Y-14.800 Z23.970 E1.3291 F480
G1 X14.802 Y-14.800 Z24.045 E1.3293
G1 X14.802 Y14.800 Z24.120 E1.3291
G1 X-14.802 Y14.800 Z24.195 E1.3293
; layer 82, Z = 24.57
; outer perimeter
G1 X-14.802 Y-14.800 Z24.270 E1.3291 F480
G1 X14.802 Y-14.800 Z24.345 E1.3293
G1 X14.802 Y14.800 Z24.420 E1.3291
G1 X-14.802 Y14.800 Z24.495 E1.3293
; layer 83, Z = 24.87
; outer perimeter
G1 X-14.802 Y-14.800 Z24.570 E1.3291 F480
G1 X14.802 Y-14.800 Z24.645 E1.3293
G1 X14.802 Y14.800 Z24.720 E1.3291
G1 X-14.802 Y14.800 Z24.795 E1.3293
; layer 84, Z = 25.17
; outer perimeter
G1 X-14.802 Y-14.800 Z24.870 E1.3291 F480
G1 X14.802 Y-14.800 Z24.945 E1.3293
G1 X14.802 Y14.800 Z25.020 E1.3291
G1 X-14.802 Y14.800 Z25.095 E1.3293
; layer 85, Z = 25.47
; outer perimeter
G1 X-14.802 Y-14.800 Z25.170 E1.3291 F480
G1 X14.802 Y-14.800 Z25.245 E1.3293
G1 X14.802 Y14.800 Z25.320 E1.3291
G1 X-14.802 Y14.800 Z25.395 E1.3293
; layer 86, Z = 25.77
; outer perimeter
G1 X-14.802 Y-14.800 Z25.470 E1.3291 F480
G1 X14.802 Y-14.800 Z25.545 E1.3293
G1 X14.802 Y14.800 Z25.620 E1.3291
G1 X-14.802 Y14.800 Z25.695 E1.3293
; layer 87, Z = 26.07
; outer perimeter
G1 X-14.802 Y-14.800 Z25.770 E1.3291 F480
G1 X14.802 Y-14.800 Z25.845 E1.3293
G1 X14.802 Y14.800 Z25.920 E1.3291
G1 X-14.802 Y14.800 Z25.995 E1.3293
; layer 88, Z = 26.37
; outer perimeter
G1 X-14.802 Y-14.800 Z26.070 E1.3291 F480
G1 X14.802 Y-14.800 Z26.145 E1.3293
G1 X14.802 Y14.800 Z26.220 E1.3291
G1 X-14.802 Y14.800 Z26.295 E1.3293
; layer 89, Z = 26.67
; outer perimeter
G1 X-14.802 Y-14.800 Z26.370 E1.3291 F480
G1 X14.802 Y-14.800 Z26.445 E1.3293
G1 X14.802 Y14.800 Z26.520 E1.3291
G1 X-14.802 Y14.800 Z26.595 E1.3293
; layer 90, Z = 26.97
; outer perimeter
G1 X-14.802 Y-14.800 Z26.670 E1.3291 F480
G1 X14.802 Y-14.800 Z26.745 E1.3293
G1 X14.802 Y14.800 Z26.820 E1.3291
G1 X-14.802 Y14.800 Z26.895 E1.3293
; layer 91, Z = 27.27
; outer perimeter
G1 X-14.802 Y-14.800 Z26.970 E1.3291 F480
G1 X14.802 Y-14.800 Z27.045 E1.3293
G1 X14.802 Y14.800 Z27.120 E1.3291
G1 X-14.802 Y14.800 Z27.195 E1.3293
; layer 92, Z = 27.57
; outer perimeter
G1 X-14.802 Y-14.800 Z27.270 E1.3291 F480
G1 X14.802 Y-14.800 Z27.345 E1.3293
G1 X14.802 Y14.800 Z27.420 E1.3291
G1 X-14.802 Y14.800 Z27.495 E1.3293
; layer 93, Z = 27.87
; outer perimeter
G1 X-14.802 Y-14.800 Z27.570 E1.3291 F480
G1 X14.802 Y-14.800 Z27.645 E1.3293
G1 X14.802 Y14.800 Z27.720 E1.3291
G1 X-14.802 Y14.800 Z27.795 E1.3293
; layer 94, Z = 28.17
; outer perimeter
G1 X-14.802 Y-14.800 Z27.870 E1.3291 F480
G1 X14.802 Y-14.800 Z27.945 E1.3293
G1 X14.802 Y14.800 Z28.020 E1.3291
G1 X-14.802 Y14.800 Z28.095 E1.3293
; layer 95, Z = 28.47
; outer perimeter
G1 X-14.802 Y-14.800 Z28.170 E1.3291 F480
G1 X14.802 Y-14.800 Z28.245 E1.3293
G1 X14.802 Y14.800 Z28.320 E1.3291
G1 X-14.802 Y14.800 Z28.395 E1.3293
; layer 96, Z = 28.77
; outer perimeter
G1 X-14.802 Y-14.800 Z28.470 E1.3291 F480
G1 X14.802 Y-14.800 Z28.545 E1.3293
G1 X14.802 Y14.800 Z28.620 E1.3291
G1 X-14.802 Y14.800 Z28.695 E1.3293
; layer 97, Z = 29.07
; outer perimeter
G1 X-14.802 Y-14.800 Z28.770 E1.3291 F480
G1 X14.802 Y-14.800 Z28.845 E1.3293
G1 X14.802 Y14.800 Z28.920 E1.3291
G1 X-14.802 Y14.800 Z28.995 E1.3293
; layer 98, Z = 29.37
; outer perimeter
G1 X-14.802 Y-14.800 Z29.070 E1.3291 F480
G1 X14.802 Y-14.800 Z29.145 E1.3293
G1 X14.802 Y14.800 Z29.220 E1.3291
G1 X-14.802 Y14.800 Z29.295 E1.3293
; layer 99, Z = 29.67
; outer perimeter
G1 X-14.802 Y-14.800 Z29.370 E1.3291 F480
G1 X14.802 Y-14.800 Z29.445 E1.3293
G1 X14.802 Y14.800 Z29.520 E1.3291
G1 X-14.802 Y14.800 Z29.595 E1.3293
; layer 100, Z = 29.97
; outer perimeter
G1 X-14.802 Y-14.800 Z29.670 E1.3291 F480
G1 X14.802 Y-14.800 Z29.745 E1.3293
G1 X14.802 Y14.800 Z29.820 E1.3291
G1 X-14.802 Y14.800 Z29.895 E1.3293
G1 X-14.802 Y-14.800 Z29.970 E1.1630
G1 X14.802 Y-14.800 Z29.970 E0.9969
G1 X14.802 Y14.800 Z29.970 E0.8307
G1 X-14.802 Y14.800 Z29.970 E0.6646
G1 E-1.0000 F1200
; layer end
; **** Replicator 2 end.gcode ****
M73 P100 ; end build progress
G1 Z155 F1000 ; send Z axis to bottom of machine
M104 S0 T0 ; cool down extruder
M127 ; stop blower fan
G162 X Y F3000 ; home XY maximum
M18 ; disable stepper
M72 P1 ; play Ta-Da song
; **** end of end.gcode ****
; Build Summary
;   Build time: 0 hours 25 minutes
;   Filament length: 547.7 mm (0.55 m)
;   Plastic volume: 1317.40 mm^3 (1.32 cc)
;   Plastic weight: 1.65 g (0.00 lb)
;   Material cost: 0.08
`;

export default gcode;